import type { Recipe } from './types';

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    name: 'Classic Avocado Toast',
    category: 'Breakfast',
    cookTime: 10,
    servings: 1,
    difficulty: 'Easy',
    calories: 250,
    protein: 8,
    image: 'https://picsum.photos/600/400',
    isFavorite: true,
    dateAdded: '2023-10-01T12:00:00Z',
    diet: ['Vegetarian', 'High-protein'],
  },
  {
    id: '2',
    name: 'Grilled Chicken Salad',
    category: 'Lunch',
    cookTime: 20,
    servings: 2,
    difficulty: 'Easy',
    calories: 450,
    protein: 40,
    image: 'https://picsum.photos/600/401',
    isFavorite: false,
    dateAdded: '2023-10-02T12:00:00Z',
    diet: ['High-protein', 'Low-carb'],
  },
  {
    id: '3',
    name: 'Spaghetti Carbonara',
    category: 'Dinner',
    cookTime: 30,
    servings: 4,
    difficulty: 'Medium',
    calories: 600,
    protein: 25,
    image: 'https://picsum.photos/600/402',
    isFavorite: true,
    dateAdded: '2023-09-15T12:00:00Z',
    diet: [],
  },
  {
    id: '4',
    name: 'Protein Power Smoothie',
    category: 'Post-workout',
    cookTime: 5,
    servings: 1,
    difficulty: 'Easy',
    calories: 350,
    protein: 30,
    image: 'https://picsum.photos/600/403',
    isFavorite: true,
    dateAdded: '2023-10-05T12:00:00Z',
    diet: ['High-protein'],
  },
  {
    id: '5',
    name: 'Keto-friendly Salmon',
    category: 'Dinner',
    cookTime: 25,
    servings: 2,
    difficulty: 'Medium',
    calories: 550,
    protein: 45,
    image: 'https://picsum.photos/600/404',
    isFavorite: false,
    dateAdded: '2023-09-28T12:00:00Z',
    diet: ['Keto', 'Low-carb', 'High-protein'],
  },
  {
    id: '6',
    name: 'Vegan Chickpea Curry',
    category: 'Dinner',
    cookTime: 40,
    servings: 4,
    difficulty: 'Medium',
    calories: 480,
    protein: 15,
    image: 'https://picsum.photos/600/405',
    isFavorite: true,
    dateAdded: '2023-09-20T12:00:00Z',
    diet: ['Vegan', 'Vegetarian'],
  },
  {
    id: '7',
    name: 'Oatmeal with Berries',
    category: 'Breakfast',
    cookTime: 15,
    servings: 1,
    difficulty: 'Easy',
    calories: 300,
    protein: 10,
    image: 'https://picsum.photos/600/406',
    isFavorite: false,
    dateAdded: '2023-10-04T12:00:00Z',
    diet: ['Vegetarian'],
  },
  {
    id: '8',
    name: 'Energy Bites',
    category: 'Snack',
    cookTime: 15,
    servings: 12,
    difficulty: 'Easy',
    calories: 120,
    protein: 4,
    image: 'https://picsum.photos/600/407',
    isFavorite: true,
    dateAdded: '2023-10-03T12:00:00Z',
    diet: ['Vegetarian'],
  },
  {
    id: '9',
    name: 'Quinoa Salad with Black Beans',
    category: 'Lunch',
    cookTime: 25,
    servings: 3,
    difficulty: 'Easy',
    calories: 400,
    protein: 18,
    image: 'https://picsum.photos/600/408',
    isFavorite: false,
    dateAdded: '2023-09-25T12:00:00Z',
    diet: ['Vegan', 'Vegetarian', 'High-protein'],
  },
  {
    id: '10',
    name: 'Hard Boiled Eggs',
    category: 'Pre-workout',
    cookTime: 12,
    servings: 2,
    difficulty: 'Easy',
    calories: 155,
    protein: 13,
    image: 'https://picsum.photos/600/409',
    isFavorite: false,
    dateAdded: '2023-10-06T12:00:00Z',
    diet: ['Vegetarian', 'Keto', 'High-protein', 'Low-carb'],
  }
];
